### ISSUE TITLE
make build fails on RHEL7

### ISSUE THREAD

**Issue by ccschneidr** [bitsensor/elastalert#51] opened 2018-10-04 13:01 UTC
Hi all,

I would like to try the elastalert-kibana-plugin and thus try to build this fork of elastalert. On RedHat Linux 7 I get the following error message from docker when running `make build`:
```
Step 1/26 : FROM alpine:latest as py-ea
Error parsing reference: "alpine:latest as py-ea" is not a valid repository/tag: invalid reference format
make: *** [build] Error 1
```
Any chance to fix that with the official RedHat Docker (version 1.13.1)? Or can the application be built without docker? The docs only state it's the easiest way, but I could not find the other ways :)

Regards,
Christian

**Comment by martijnrondeel** [comment] 2018-10-04 13:13
You can try [these](https://github.com/bitsensor/elastalert/tree/feature/enhancement#installation-using-npm-and-manual-elastalert-setup) (possibly outdated) instructions for a manual installation. We no longer support non-Docker installations however.

The error itself is a duplicate of #47. I will update the docs to make clear Docker 17.05+ is required and Docker is the only way to currently install the ElastAlert server.

**Closed by martijnrondeel** 2018-10-04 13:13 UTC

**Comment by ccschneidr** [comment] 2018-10-04 13:56
Oh, thanks, for some reason I could not find the other issue. Seems I'll need to find a way to install the non-RedHat docker then :/
