### ISSUE TITLE
Client request error: connect ECONNREFUSED 127.0.0.1:3030

### ISSUE THREAD

**Issue by yangcaixing** [bitsensor/elastalert#97] opened 2019-06-06 09:38 UTC
Hi all,
I encountered an error after install the elastalert-kibana-plugin as below, I have pre-installed the ElastAlert Server with this command "pip install "elastalert>=0.2.0b", but I don't know if need some configuration for the elastalert server, I don't use docker to setup the ELK and elastalert, so if anyone have the same issue as me, I'm stuck in it, looking forward your help, thanks in advance.
![elastalert](https://user-images.githubusercontent.com/41502299/59023219-e1aed180-8881-11e9-806b-aa4f2a25f71c.png)

**Comment by yangcaixing** [comment] 2019-06-06 10:26
and after I installed the elastalert server with docker image, it also display the bellow error, I also add configuration"elastalert-kibana-plugin.serverHost: 127.0.0.1, elastalert-kibana-plugin.serverPort: 9200" to the /etc/kibana/kibana.yml, if anyone can help me ,thanks a lot.
![elastalert-server](https://user-images.githubusercontent.com/41502299/59026253-86cca880-8888-11e9-919e-3d2b68f674cd.png)

**Comment by martijnrondeel** [comment] 2019-06-11 09:23
Closing this as a duplicate of https://github.com/bitsensor/elastalert-kibana-plugin/issues/113

**Closed as completed by martijnrondeel** 2019-06-11 09:23 UTC
